sudo: required
 language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  # login to docker registries
  - echo "$ DOCKER_PASSWORD" | docker login -u "$ DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - npm install
script:
  - npm test