sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # login to heroku
  - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
install:
  # install deps
  - docker-compose build
  - docker-compose up -d
script:
  - docker exec -ti backend_nodejs npm run test
  # Tagging the image to be used with Heroku
  - docker tag rakhma/backend_nodejs registry.heroku.com/node-docker-travis/web
after_script:
  - docker-compose stop
deploy:
  provider: script
  script:
    - bash scripts/deploy_production.sh
  on:
    branch: master
deploy:
  provider: script
  script:
    - bash scripts/deploy_staging.sh
  on:
    branch: staging