sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  # Heroku CLI Install
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
install:
  # install deps
  - docker-compose build
  - docker-compose up -d
script:
  - docker exec -ti backend_nodejs npm run test
  # Tagging the image to be used with Heroku
  - docker tag rakhma/backend_nodejs registry.heroku.com/node-docker-travis/web
after_script:
  - docker-compose stop
deploy:
  provider: script
  script:
    - bash scripts/deploy_production.sh
  on:
    branch: master
deploy:
  provider: script
  script:
    - bash scripts/deploy_staging.sh
  on:
    branch: heroku
deploy:
  #specify the provider 
  provider: elasticbeanstalk
  #specify the region where the provider is present, You can get this from the AWS ElasticBeanstalk dashboard
  region: "us-east-2"
  #Specify the application name in AWS elastic beanstalk
  app: "Travis docker AWS"
  #Specify the environment name in AWS elastic beanstalk
  env: "TravisDockerAws-env"
  #Specify the Bucket name which is the name of the S3 (storage) which is created as part of Elastic beanstalk in AWS
  bucket_name: "elasticbeanstalk-us-east-2-736607720718"
  #specify the path of the Bucket , this will be similar to the App name above
  bucket_path: "Travis docker AWS"
  #specify when you want to deploy (we want to deploy only when we push code to master branch)
  on:
    branch: aws
  #Specify the Environment variable name from which Travis can get the ACCESS_KEY to AWS
  access_key_id: $AWS_ID
  #Specify the Environment variable name from which Travis can get the SECRET_KEY to AWS
  secret_access_key:
    secure: "$AWS_PASSWORD"