sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - docker-compose build
  - docker-compose up -d
script:
  - docker exec -ti backend_nodejs npm run test
after_script:
  - docker-compose stop
deploy:
  provider: script
  script: |
    docker push rakhma/backend_nodejs && \
    docker push rakhma/backend_nodejs2
  on:
    branch: master