version: '3'
services:
  mongodb:
    container_name: database_mongodb
    image: mongo
    ports:
      - "27017:27017"
  nodejs:
    container_name: backend_nodejs
    image: rakhma/backend_nodejs
    environment:
      - SERVER_PORT="80"
    build: .
    ports:
      - "80:80"
    links:
      - mongodb